numpy
  2D array

In [12]:
import numpy as np

fancy indexing

In [13]:
import numpy as np
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a<=6

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [15]:
a[a<=6]

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
a=np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

use of mask

In [17]:
mask=(a%2==0)
a[mask]=-1
print(a)

[-1  1 -1  3 -1  5]


aggregate function

In [18]:
a=np.array([10,20,35,40,55])
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))

160
32.0
10
55


use of all and any

In [19]:
np.all(a<30)

np.False_

In [20]:
np.any(a<30)

np.True_

where clause

In [21]:
a=np.array([10,20,35,40,55])
b=np.where(a%2!=0,-1,1)        #syntax  where( condition,  ifTrue,  ifFalse)
b

array([ 1,  1, -1,  1, -1])

sorting

In [22]:
a=np.array([100,210,50,140,155])
b=np.sort(a)
b

array([ 50, 100, 140, 155, 210])

matrix multiplication

In [33]:
a=np.arange(1,13).reshape(3,4)
b=np.arange(2,14).reshape(4,3)
print(a,"\n\n",b)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


methods of multiplication

In [30]:
c=np.dot(a,b)
c

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [31]:
c=a@b
c

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [32]:
c=np.matmul(a,b)
c

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])